### ISSUE TITLE
hey can help

### ISSUE THREAD

**Issue by iProB1** [KaptainWutax/SeedCracker#208]
how can i update it to 1.16.5

**Comment by PhoenixXKN** [comment]
first step would be actually searching through the other issues, and the second one would be not spamming the issues section on github with questions about how to use it, it is there for actual issues with the code and not these kinds of questions. I don't even understand what the problem is supposed to be, the .4 jar works fine with 1.16.5 and i even managed to use it for some of the earlier 1.17 snapshots.
