### ISSUE TITLE
1.16 version broken by 20w20b mappings

### ISSUE THREAD

**Issue by postout** [KaptainWutax/SeedCracker#40]
No longer compatible with newest version of 1.16 snapshot (20w20b). Mod causes hang in single player, and errors out when attempting to join multiplayer world.

**Comment by aria1th** [comment]
Tried build gradlew, got same result:
Internal Exception: java.lang.ClassCastException: net.minecraft.class_3248 cannot be cast to net.minecraft.class_2602
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1942

Basically, class_1942 seems to be missing. So I've checked mappings, and found difference between 18a and 20b: (used intermediary mapping - mapping.tiny files), 

MISSING
CLASS	boz	net/minecraft/class_1942
CLASS	bp	net/minecraft/class_2076
CLASS	bp$a	net/minecraft/class_2076$class_2078

...and so on...

**Comment by KaptainWutax** [comment]
I don't offer support for unreleased versions. I will be updating the repo when I find the time, doesn't seem like much, just the SHA2 class changed.
