### ISSUE TITLE
Anti-Xray issue on Multiplayer

### ISSUE THREAD

**Issue by zykrahgaming** [KaptainWutax/SeedCracker#58]
Anti-xray makes the client think there is alot of emerald everywhere, and even when i turn off EMERALD_ORE the overlay is still there and it still contributes towards the total bits. Not sure if i'm doing it incorrectly though.

**Comment by KaptainWutax** [comment]
Clear the data /seed data clear.

**Comment by zykrahgaming** [comment]
tried but the emerald ore still highlights and contributes to the total bits, making my bits go into the thousands

**Comment by Neffc** [comment]
You have to clear the data AND disable the finder for emerald ore, otherwise it's just going to start collecting emerald ore data again.

**Comment by zykrahgaming** [comment]
i did both

**Comment by kevindaze** [comment]
U need to use /seed data clear then /seed finder type EMERALD_ORE _OFF

**Comment by Neffc** [comment]
If you're still getting incorrect data then either you didn't disable the emerald ore finder, or it's not actually the emerald ore finder that you're seeing

**Comment by zykrahgaming** [comment]
hold on i will test one more time, thanks for the suggestion btw

**Comment by zykrahgaming** [comment]
it no longer highlights emerald ore, but dungeon finding doesnt work and neither does the end pillars

**Comment by evrooije** [comment]
I was able to make it work on a 1.16.1 (paper) anti-xray server. Steps were: 1) find a place that has never been generated before!! (I have various locations with 1.14 and 1.15 map generated data, does not work there) 2) do /seed data clear, then /seed finder type EMERALD_ORE OFF and just to be 100% sure I then did a /seed finder type DUNGEONS ON (but I think the latter is on by default nowadays?) 3) walk around for about 20-30 minutes. It found a seed, I entered it into amidst, looked for my base and the biomes/ outlines match with were my base is. It finally worked, but with anti-xray servers and old map data it is a bit harder to make it work. So have patience since probably the emerald finder type speeds things up(?) and make sure you get the prereqs right... Hth and good luck! :-)

**Comment by zykrahgaming** [comment]
@evrooije did you use dungeon finder? i tried but it didnt detect any dungeons because antixray fakes mossy stone im pretty sure

**Comment by KaptainWutax** [comment]
If anti-xray fakes even dungeons you can only really use structures and end pillars then.

**Comment by zykrahgaming** [comment]
Also, to be clear, the 1.16.1 PaperMC Anti-XRAY is in engine-mode: 2 (which can be found in the paper.yml). That's the one that fakes ores being everywhere.

**Comment by evrooije** [comment]
I used dungeon finder. IIRC anti-xray can fake blocks as long as they are not exposed to air. Faked blocks exposed to air through digging get changed to the proper ore. I'm not sure if dungeons can be faked since there is air inside the dungeon, but am not 100% sure. During my walk around I noticed a few dungeons where the plateau was outlined and a couple of mob spawners only without the outline of the plateau. The server where I play fakes ores everywhere, when it is laggy I can see emerald, diamond, lapis, etc. before disappearing a moment later due to exposure to air. And I got it to work, through patience. If you find that your anti-xray fakes dungeons, then like KaptainWutax says, disable the finder type and find other structures like desert temples, shipwrecks, monuments, etc. that cannot be faked.

**Comment by zykrahgaming** [comment]
I had a theory... basically, anti-x-ray fakes blocks that aren't exposed to air. So, the issue is that some blocks (of the dungeon floor) have blocks on top of them (the walls of the dungeon) and therefore are being faked (because they are obstructed). The solution is to find a dungeon (Not hard, because the mod still highlights spawners) and then make sure all the blocks of the floor are exposed. After this, you need to move outside of the "render" distance of the dungeon. Then you need to clear the data, turn off emeralds, turn on dungeon, make sure you aren't at 0 bits (if not then make sure you a rep standing still while doing commands and try again) and then walk towards the dungeon. If all works correctly, it should detect the dungeon floor as well!

**Comment by zykrahgaming** [comment]
Adding on from above:

I finally got it working on a server.

1. Find a dungeon (The mod highlights mob spawners, so it should be simple)
2. Light it up, then mine out the blocks of the dungeon wall that are on the same y level as the mob spawner (1 block above the floor). Make sure all blocks of the floor (cobblestone and mossy cobblestone) are at least exposed to 1 air block.
3. Go back to surface and move away until the dungeon goes out of render distance.
4. Stand still and type `/seed data clear`, then instantly type `/seed finder type EMERALD_ORE OFF`. Type `/seed data bits` and make sure it is at 0. If not, then just repeat until it is at 0. 
5. Type `/seed finder type DUNGEON ON`.
6. Walk back in the direction of where the dungeon was. If it says short-cutting to dungeons, then you are successful!
7. Build up your bit count by walking around alot and make sure the "found structure seed" comes up (there should be more than one)
8. Go to the end (to get the hashed world seed) and it should start finding the world seed.
9. Voila! You now have the world seed!

also @KaptainWutax i noticed that step 8 shouldnt be necessary... i think it has to do with the hashed world seed not being saved after `/seed data clear`. I'm not sure if that's intentional, but the mod wouldn't find the seed until i went to the end (where the hashed seed was found again) 

As a last thought, you could try going to the nether instead of the end to get the hashed world seed... Havent tested tho.

**Comment by zykrahgaming** [comment]
Lastly, as of update 0.2.1, end pillars now work as an alternative to dungeon cracking, however, dungeon cracking still poses as a better option (especially on spigot/paper/non-vanilla servers, where the end and overworld seed may differ).

**Comment by KaptainWutax** [comment]
Nice one @zykrahgaming! And yea clearing data should probably leave the hashed seed intact.
